#include <iostream>
#include <stdexcept>
using namespace std;

int dividir(int a, int b) {
    if (b == 0) {
        throw runtime_error("Divisi√≥n por cero no permitida");
    }
    return a / b;
}

int main() {
    try {
        cout << dividir(10, 0) << endl;
    } catch (const runtime_error& e) {
        cout << "Error: " << e.what() << endl;
    }
    return 0;
}
